### ISSUE TITLE
Option to crop frame around brightest pixel

### ISSUE THREAD

**Issue by vandalt** [kammerje/xara#3]
For NIRISS, there are 4 rows of reference pixels which should be discarded before doing the analysis. To discard these and keep a square image, it would be good to have a "crop" option along with the "roll" one for integer-pixel recentering.

Also, the external fourier-plane bad pixel script we are using currently does a crop around the brightest pixel (not a roll) such that bad pixels outside the cropped image are left untouched (but the full image is saved). We might want to modify how bad pixel correction centering/cropping is handled when integrating it here.

For now, I am cropping the image before passing them through the pipeline because I already have a function that does if for AMI. I'm opening an issue to remember to address this in the near future.

**Comment by kammerje** [comment]
I believe this was fixed by PR #7, right? I think cropping the four rows of NIRISS reference pixels is the right approach here.

**Comment by vandalt** [comment]
Yes, indeed this was fixed by #7
